# These are supported funding model platforms

github: [xand0dev] # Replace with your GitHub username if you have GitHub Sponsors enabled
patreon: xand0dev
ko_fi: xand0dev
buy_me_a_coffee: xand0dev
custom: ["https://buymeacoffee.com/xand0dev", "https://patreon.com/xand0dev"]
